### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'spades'; and other notes on SPAdes

### ISSUE THREAD

**Issue by SethMusker** [faircloth-lab/itero#10]
Hi Brant,
Had the following error on sample 11 out of 39 (the first ten ran fine). 
```
2020-05-09 18:25:07,173 - itero - INFO - Assembling
Traceback (most recent call last):
  File "/scratch/mskset001/conda_scratch/envs/itero/bin/itero", line 18, in <module>
    sys.exit(main())
  File "/scratch/mskset001/conda_scratch/envs/itero/lib/python2.7/site-packages/itero/cli/main.py", line 62, in main
    args.func(args, p)
  File "/scratch/mskset001/conda_scratch/envs/itero/lib/python2.7/site-packages/itero/cli/sub_assemble_local.py", line 44, in run_local_assembly
    merged.main(args, parser, mpi=False)
  File "/scratch/mskset001/conda_scratch/envs/itero/lib/python2.7/site-packages/itero/assemble/merged.py", line 150, in main
    pool.map(common.initial_assembly, tasks)
  File "/scratch/mskset001/conda_scratch/envs/itero/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/scratch/mskset001/conda_scratch/envs/itero/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
ConfigParser.NoSectionError: No section: 'spades'
```

I was perhaps silly in that I edited itero.conf to increase spades memory to 8GB (each core has 9GB) for future runs while the job was running, assuming that itero.conf wouldn't need to be read once a job had initiated. Maybe that was the problem? Interestingly I'm also running another job with `--allow-multiple-contigs` as itero has been dropping many genes (many samples end up with <10 genes out of 130) and this is still going fine with later samples showing that spades memory is set to 8GB.

On that note I think the loss of genes has to do with the kmer setting. Many samples seem to end up with one long contig and then a few (sometimes very many) small contigs that haven't been connected. It seems possible to specify many kmer values in the spades section of itero.conf (?). Perhaps better would be to have a single kmer value for the initial iterations and then use more for the final round(s)? 

Finally (and sorry for clumping many things in one post) I've noticed that in the last iteration the spades log reports don't show that `--careful` has been turned on or that `--only-assembly` is omitted:

> System information:
>   SPAdes version: 3.12.0
>   Python version: 2.7.15
>   OS: Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
> 
> Output dir: /scratch/mskset001/[_etc._]
> Mode: ONLY assembling (without read error correction)
> Debug mode is turned OFF
> 
> Dataset parameters:
>   Multi-cell mode (you should set '--sc' flag if input data was obtained with MDA (single-cell) technology or --meta flag if processing metagenomic dataset)
>   Reads:
>     Library number: 1, library type: paired-end
>       orientation: fr
>       left reads: ['/scratch/mskset001/[_etc._].read1.fastq']
>       right reads: ['/scratch/mskset001/[_etc._].read2.fastq']
>       interlaced reads: not specified
>       single reads: ['/scratch/mskset001/[_etc._]singleton.fastq']
>       merged reads: not specified
> Assembly parameters:
>   k: [33]
>   Repeat resolution is enabled
>   Mismatch careful mode is turned OFF
>   MismatchCorrector will be SKIPPED
>   Coverage cutoff is turned ON and threshold is 5.0
> Other parameters:
>   Dir for temp files: /scratch/mskset001/[_etc._]/tmp
>   Threads: 1
>   Memory limit (in Gb): 8

My "iter-final" folder never has any assemblies in it, just the last iteration's contigs and a new .bam file (with associated indeces and logs). Is this the intended behaviour?
Cheers

**Comment by brantfaircloth** [comment]
1. The `No Section` error may have resulted because you edited the file.  Generally, if the program has run over X out of Y samples and X is a somewhat big number, the error is probably in something about the setup of the run (bad files, bad config, too little RAM, etc.) than in the program (but this is not always true!), and just hit an error that affects a particular assembly.  For example, one thing we always do is downsample our reads to some maximum per sample... then it's easier to deal with RAM needs, etc.

2. The loss of genes may have to do with kmer setting.  You can adjust kmer value in either the config file that comes with the package (`itero/config/itero.conf`), or in a user-specific config file that you create at `~/.itero/itero.conf`, which contains the same entries (you can include only the parameters you are changing, if you want):
```
[executables]
bedtools:$CONDA_PREFIX/bin/bedtools
bwa:$CONDA_PREFIX/bin/bwa
gawk:$CONDA_PREFIX/bin/gawk
grep:$CONDA_PREFIX/bin/grep
samtools:$CONDA_PREFIX/bin/samtools
spades:$CONDA_PREFIX/bin/spades.py

[spades]
kmer:33
coverage_cutoff:5
# 'memory' is RAM used per proc in GB
memory:2
```

3. Finally, the iter-final folder is structured as intended - the contigs and a bam file for them, so you can do things like compute coverage.

**Comment by SethMusker** [comment]
1. I reran the failed sample without any problem so I think it was the conf file edit. Thanks. 
2. Cool.
3. The reason I asked was that in your `spades.py` you have these lines:
 
```
    # turn off error correction for non-final rounds, turn on error-correction
    # for final round and also use --careful assembly option (both of these are
    # slower)
    if not iteration == 'final':
        cmd1.append("--only-assembler")
    if iteration == 'final':
        cmd1.append("--careful")
```

but it seems that isn't happening as my spades log files for the last numbered iterations state "Mismatch careful mode is turned OFF; MismatchCorrector will be SKIPPED".
Unless I'm misunderstanding something?
